export const INTELLA_MESSAGE_TYPES = {
  SESSION_ID_ASSIGNED: "SESSION_ID_ASSIGNED",
  SESSION_STARTED: "SESSION_STARTED",
  SESSION_ENDED: "SESSION_ENDED",
  SESSION_ERROR: "SESSION_ERROR",
  SESSION_REPORTING: "SESSION_REPORTING",
  SESSION_REPORTED: "SESSION_REPORTED",
} as const;
export type IntellaMessageType = keyof typeof INTELLA_MESSAGE_TYPES;
